### PR TITLE
Removed rules that are match wikipedia default config

### PR DESCRIPTION
**Pull request by Pchelolo**
In our continuing attempts to bring the configs together, I've looked into the rules that match in both this config and the wikimedia one we inherit and removed the matching rules.

cc @wikimedia/services

### CODE REVIEW

**Comment by Pchelolo** [comment]
WAAAAIT on merging, I've got an idea.

**Comment by Pchelolo** [comment]
Although, I can delete more.

**Comment by jdforrester** [comment]
If we wanted to be really sure we were minimally-spanning, we could merge these rules into a sub-profile of eslint-config-wikimedia (`eslint-config-wikimedia/services`, perhaps?) with unit tests asserting that we have the exact behaviour we want, and no duplicated rules?

**Comment by Pchelolo** [comment]
> If we wanted to be really sure we were minimally-spanning, we could merge these rules into a sub-profile of eslint-config-wikimedia (eslint-config-wikimedia/services, perhaps?) with unit tests asserting that we have the exact behaviour we want, and no duplicated rules?

@jdforrester I've make a little tool to make sure we get rid of all the unnesessary ones regarding this and wikimedia config. I'm still looking for already made tools that do it, but ye, having some unit testing there would be nice - that's where I was going with my little tool. I guess next step?

**Comment by Pchelolo** [comment]
The purpose of this one is that it seems we're slowly converging these, so I've just removed the obvious opportunities for converging to remove a bit of confusion. Eventually we want to make the diff as small as possible

**Comment by Pchelolo** [comment]
Neat. I'm all for merging the 2. 

One thing that might not be handy is peer dependencies - the services one has jsdoc and json plugins as peer dependencies, the Wikimedia one does not - and we would need to declare them. Or not... hm..

**Comment by jdforrester** [comment]
We added the qunit peer dependency for the qunit one, not a problem to require the lot IMO.

**Comment by Pchelolo** [comment]
It actually was a bit of a pain in the service world due to how peer deps work in npm - makes automatic versions bumping quite a pain as you always end up with something wrong. 

I'm wondering whether we can actually set them as normal dependencies and never bother explicitly declaring them in the clients package.json

**Pull request merged**
