### PR TITLE
Require `case` to be indented; release v2.2.4

### PR DESCRIPTION
**Pull request by d00rman**

### CODE REVIEW

**Comment by d00rman** [comment]
cc @Pchelolo

**Comment by d00rman** [comment]
Not sure why `npm install` fails miserably for Node v4.x

**Comment by Pchelolo** [comment]
I don't have personal preferences on intending the `case`.

The `npm install` fails probably because of a mismatch in peer ad dev dependency version on the `eslint-config-wikipedia` package.

**Comment by d00rman** [comment]
@Pchelolo fixed the dep and added node 8 testing.

**Comment by d00rman** [comment]
@Pchelolo could you please tag and release as I'm not a maintainer of the package on `npmjs` ?

**Comment by Pchelolo** [comment]
@d00rman done. And now you're a maintainer as well.

**Pull request merged**
