### PR TITLE
Update 'quotes' and 'quote-props' rules

### PR DESCRIPTION
**Pull request by mdholloway**
These should be inherited from eslint-config-wikimedia.

### CODE REVIEW

**Comment by jdforrester** [comment]
These rules were inherited from the main Wikimedia ruleset and explicitly disabled. Presumably whoever did that had a reason at the time, which is why I didn't push this. :-)

Happy for it to go ahead if it is (but maybe we should upstream the `avoidEscape` setting for `quotes`, rather than re-set most of it to the same value as upstream?).

**Comment by Pchelolo** [comment]
> maybe we should upstream the avoidEscape setting for quotes, rather than re-set most of it to the same value as upstream?

+1 to this.

**Comment by mdholloway** [comment]
Done, see https://github.com/wikimedia/eslint-config-wikimedia/pull/92

**Comment by mdholloway** [comment]
It looks like this is being superseded by https://github.com/wikimedia/eslint-config-node-services/pull/30 and ideas being discussed therein.

**Pull request closed without merging**
